import { create } from "zustand";
import { EventStatus, type Event } from "@/types/firebase";
import eventDigital from "@/assets/event-digital.jpg";
import eventSelfDefense from "@/assets/event-selfdefense.jpg";
import eventFinance from "@/assets/event-finance.jpg";
import eventEntrepreneur from "@/assets/event-entrepreneur.jpg";
import eventHealth from "@/assets/event-health.jpg";

const now = Date.now();
const images = [eventDigital, eventSelfDefense, eventFinance, eventEntrepreneur, eventHealth];
const img = (i: number): import("@/types/firebase").ImageAsset => ({
  url: images[i % images.length] as string,
  path: "",
});

const initialEvents: Event[] = [
  // ── Upcoming Events (12) ──
  {
    id: "u1",
    title: "Digital Literacy Workshop",
    startDateTime: new Date("2026-04-15T10:00:00").getTime(),
    endDateTime: new Date("2026-04-15T16:00:00").getTime(),
    venueName: "Community Hall, Sector 12, Jaipur",
    venueUrl: "https://maps.google.com/?q=Community+Hall+Sector+12+Jaipur",
    description: "Learn essential computer skills, internet safety, and how to use digital payment platforms.",
    status: EventStatus.FILLING_FAST,
    registrationUrl: "https://forms.google.com",
    coverImage: img(0),
    hostName: "Aagaj Foundation",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u2",
    title: "Self-Defence Training Camp",
    startDateTime: new Date("2026-04-22T07:00:00").getTime(),
    endDateTime: new Date("2026-04-22T11:00:00").getTime(),
    venueName: "Rajiv Gandhi Stadium, Lucknow",
    venueUrl: "https://maps.google.com/?q=Rajiv+Gandhi+Stadium+Lucknow",
    description: "A hands-on self-defence camp for women of all ages. Professional trainers will guide you.",
    status: EventStatus.ONLINE,
    registrationUrl: "https://forms.google.com",
    coverImage: img(1),
    hostName: "Aagaj Foundation",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u3",
    title: "Financial Independence Seminar",
    startDateTime: new Date("2026-05-05T11:00:00").getTime(),
    endDateTime: new Date("2026-05-05T15:00:00").getTime(),
    venueName: "Town Hall, Patna",
    venueUrl: "https://maps.google.com/?q=Town+Hall+Patna",
    description: "Understand savings, investments, and government schemes designed for women.",
    status: EventStatus.REGISTRATION_CLOSED,
    registrationUrl: "https://forms.google.com",
    coverImage: img(2),
    hostName: "Aagaj Foundation",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u4",
    title: "Women in Leadership Summit",
    startDateTime: new Date("2026-05-12T09:00:00").getTime(),
    endDateTime: new Date("2026-05-12T17:00:00").getTime(),
    venueName: "ITC Grand, Kolkata",
    venueUrl: "https://maps.google.com/?q=ITC+Grand+Kolkata",
    description: "A day-long summit featuring inspiring women leaders sharing their journeys and insights.",
    status: EventStatus.FILLING_FAST,
    registrationUrl: "https://forms.google.com",
    coverImage: img(3),
    hostName: "Aagaj Foundation",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u5",
    title: "Nutrition & Wellness Workshop",
    startDateTime: new Date("2026-05-20T10:00:00").getTime(),
    endDateTime: new Date("2026-05-20T14:00:00").getTime(),
    venueName: "District Hospital, Bhopal",
    venueUrl: "https://maps.google.com/?q=District+Hospital+Bhopal",
    description: "Expert-led sessions on balanced nutrition, maternal health, and mental wellness practices.",
    status: EventStatus.ONLINE,
    registrationUrl: "https://forms.google.com",
    coverImage: img(4),
    hostName: "Aagaj Foundation",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u6",
    title: "Legal Awareness Camp",
    startDateTime: new Date("2026-06-01T10:00:00").getTime(),
    endDateTime: new Date("2026-06-01T14:00:00").getTime(),
    venueName: "Panchayat Bhawan, Ranchi",
    venueUrl: "https://maps.google.com/?q=Panchayat+Bhawan+Ranchi",
    description: "Know your legal rights — property, domestic violence, workplace harassment, and more.",
    status: EventStatus.FILLING_FAST,
    registrationUrl: "https://forms.google.com",
    coverImage: img(0),
    hostName: "Aagaj Foundation",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u7",
    title: "Art & Craft Skill Development",
    startDateTime: new Date("2026-06-10T09:00:00").getTime(),
    endDateTime: new Date("2026-06-10T16:00:00").getTime(),
    venueName: "Craft Village, Udaipur",
    venueUrl: "https://maps.google.com/?q=Craft+Village+Udaipur",
    description: "Hands-on training in handicrafts, block printing, and pottery for income generation.",
    status: EventStatus.ONLINE,
    registrationUrl: "https://forms.google.com",
    coverImage: img(1),
    hostName: "Aagaj Foundation",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u8",
    title: "Cyber Safety for Women",
    startDateTime: new Date("2026-06-18T11:00:00").getTime(),
    endDateTime: new Date("2026-06-18T15:00:00").getTime(),
    venueName: "IT Park Auditorium, Pune",
    venueUrl: "https://maps.google.com/?q=IT+Park+Auditorium+Pune",
    description: "Learn to protect yourself from online fraud, cyberstalking, and social media misuse.",
    status: EventStatus.FILLING_FAST,
    registrationUrl: "https://forms.google.com",
    coverImage: img(2),
    hostName: "Aagaj Foundation",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u9",
    title: "Menstrual Hygiene Workshop",
    startDateTime: new Date("2026-06-25T10:00:00").getTime(),
    endDateTime: new Date("2026-06-25T13:00:00").getTime(),
    venueName: "Government School, Varanasi",
    venueUrl: "https://maps.google.com/?q=Government+School+Varanasi",
    description: "Breaking taboos — free sanitary kits, awareness sessions, and open Q&A for young women.",
    status: EventStatus.ONLINE,
    registrationUrl: "https://forms.google.com",
    coverImage: img(3),
    hostName: "Aagaj Foundation",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u10",
    title: "Career Counselling Drive",
    startDateTime: new Date("2026-07-05T09:00:00").getTime(),
    endDateTime: new Date("2026-07-05T16:00:00").getTime(),
    venueName: "University Campus, Chandigarh",
    venueUrl: "https://maps.google.com/?q=University+Campus+Chandigarh",
    description: "One-on-one career guidance, resume building, and interview prep for young women graduates.",
    status: EventStatus.FILLING_FAST,
    registrationUrl: "https://forms.google.com",
    coverImage: img(4),
    hostName: "Aagaj Foundation",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u11",
    title: "Rural Women Empowerment Meet",
    startDateTime: new Date("2026-07-15T10:00:00").getTime(),
    endDateTime: new Date("2026-07-15T15:00:00").getTime(),
    venueName: "Community Center, Ajmer",
    venueUrl: "https://maps.google.com/?q=Community+Center+Ajmer",
    description: "Connecting rural women with government welfare schemes, SHG formation, and micro-finance.",
    status: EventStatus.ONLINE,
    registrationUrl: "https://forms.google.com",
    coverImage: img(0),
    hostName: "Aagaj Foundation",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u12",
    title: "Spoken English Bootcamp",
    startDateTime: new Date("2026-07-25T09:00:00").getTime(),
    endDateTime: new Date("2026-07-25T14:00:00").getTime(),
    venueName: "Public Library Hall, Indore",
    venueUrl: "https://maps.google.com/?q=Public+Library+Hall+Indore",
    description: "A 5-hour intensive spoken English bootcamp to boost confidence and employability.",
    status: EventStatus.FILLING_FAST,
    registrationUrl: "https://forms.google.com",
    coverImage: img(1),
    hostName: "Aagaj Foundation",
    createdAt: now,
    updatedAt: now,
  },

  // ── Past / Completed Events (8) ──
  {
    id: "p1",
    title: "Entrepreneurship Bootcamp 2025",
    startDateTime: new Date("2025-11-10T09:00:00").getTime(),
    endDateTime: new Date("2025-11-10T17:00:00").getTime(),
    venueName: "Convention Center, Delhi",
    venueUrl: "https://maps.google.com/?q=Convention+Center+Delhi",
    description: "Intensive bootcamp for aspiring women entrepreneurs across six districts.",
    status: EventStatus.COMPLETED,
    registrationUrl: "",
    coverImage: img(3),
    imageAssets: [img(3), img(4), img(0), img(1), img(2)],
    hostName: "Aagaj Foundation",
    metrics: [
      { label: "Women Trained", value: "120" },
      { label: "Businesses Launched", value: "28" },
      { label: "Districts", value: "6" },
    ],
    testimonials: [
      {
        description: "This workshop changed my life. I started my own handicraft business and now support my entire family.",
        username: "Sunita Devi, Participant, Patna",
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p2",
    title: "Women's Health Awareness Camp",
    startDateTime: new Date("2025-09-15T09:00:00").getTime(),
    endDateTime: new Date("2025-09-15T17:00:00").getTime(),
    venueName: "Community Hall, Lucknow",
    venueUrl: "https://maps.google.com/?q=Community+Hall+Lucknow",
    description: "Health awareness camp covering regular checkups, nutrition, and mental wellness.",
    status: EventStatus.COMPLETED,
    registrationUrl: "",
    coverImage: img(4),
    imageAssets: [img(4), img(2), img(1), img(0), img(3)],
    hostName: "Aagaj Foundation",
    metrics: [
      { label: "Women Reached", value: "350" },
      { label: "Free Checkups", value: "200" },
      { label: "Villages Covered", value: "12" },
    ],
    testimonials: [
      {
        description: "For the first time, I understood the importance of regular health checkups. Thank you, Aagaj!",
        username: "Meena Kumari, Participant, Lucknow",
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p3",
    title: "Self-Defence Training — Batch II",
    startDateTime: new Date("2025-08-20T07:00:00").getTime(),
    endDateTime: new Date("2025-08-20T12:00:00").getTime(),
    venueName: "Sports Complex, Agra",
    venueUrl: "https://maps.google.com/?q=Sports+Complex+Agra",
    description: "Second batch of our popular self-defence training. 100+ women participated.",
    status: EventStatus.COMPLETED,
    registrationUrl: "",
    coverImage: img(1),
    imageAssets: [img(1), img(0), img(3), img(4)],
    hostName: "Aagaj Foundation",
    metrics: [
      { label: "Participants", value: "110" },
      { label: "Trainers", value: "8" },
    ],
    testimonials: [
      {
        description: "I feel so much more confident walking alone. Every woman should attend this camp.",
        username: "Rani Sharma, Participant, Agra",
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p4",
    title: "Digital Payments Awareness Drive",
    startDateTime: new Date("2025-07-10T10:00:00").getTime(),
    endDateTime: new Date("2025-07-10T14:00:00").getTime(),
    venueName: "Block Office, Gaya",
    venueUrl: "https://maps.google.com/?q=Block+Office+Gaya",
    description: "Teaching rural women how to use UPI, mobile banking, and protect against digital fraud.",
    status: EventStatus.COMPLETED,
    registrationUrl: "",
    coverImage: img(0),
    imageAssets: [img(0), img(2), img(4)],
    hostName: "Aagaj Foundation",
    metrics: [
      { label: "Women Trained", value: "85" },
      { label: "Villages", value: "9" },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p5",
    title: "Financial Literacy for SHGs",
    startDateTime: new Date("2025-06-05T11:00:00").getTime(),
    endDateTime: new Date("2025-06-05T16:00:00").getTime(),
    venueName: "Gram Panchayat, Muzaffarpur",
    venueUrl: "https://maps.google.com/?q=Gram+Panchayat+Muzaffarpur",
    description: "Workshops on savings, micro-finance, and bookkeeping for self-help group members.",
    status: EventStatus.COMPLETED,
    registrationUrl: "",
    coverImage: img(2),
    imageAssets: [img(2), img(3), img(1), img(0)],
    hostName: "Aagaj Foundation",
    metrics: [
      { label: "SHGs Trained", value: "24" },
      { label: "Members Reached", value: "310" },
    ],
    testimonials: [
      {
        description: "Now our SHG keeps proper accounts. We even got a bank loan after this training!",
        username: "Kavita Singh, SHG Leader, Muzaffarpur",
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p6",
    title: "Maternal Health Camp",
    startDateTime: new Date("2025-05-10T09:00:00").getTime(),
    endDateTime: new Date("2025-05-10T15:00:00").getTime(),
    venueName: "PHC, Sitamarhi",
    venueUrl: "https://maps.google.com/?q=PHC+Sitamarhi",
    description: "Free antenatal checkups, iron supplements distribution, and newborn care education.",
    status: EventStatus.COMPLETED,
    registrationUrl: "",
    coverImage: img(4),
    imageAssets: [img(4), img(0), img(3)],
    hostName: "Aagaj Foundation",
    metrics: [
      { label: "Women Checked", value: "175" },
      { label: "Kits Distributed", value: "175" },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p7",
    title: "Handicraft Exhibition & Sale",
    startDateTime: new Date("2025-04-01T10:00:00").getTime(),
    endDateTime: new Date("2025-04-02T18:00:00").getTime(),
    venueName: "Dilli Haat, New Delhi",
    venueUrl: "https://maps.google.com/?q=Dilli+Haat+New+Delhi",
    description: "Two-day exhibition showcasing handicrafts made by women trained through Aagaj programmes.",
    status: EventStatus.COMPLETED,
    registrationUrl: "",
    coverImage: img(3),
    imageAssets: [img(3), img(1), img(2), img(0), img(4)],
    hostName: "Aagaj Foundation",
    metrics: [
      { label: "Stalls", value: "40" },
      { label: "Revenue Generated", value: "₹3.2L" },
      { label: "Artisans", value: "65" },
    ],
    testimonials: [
      {
        description: "Selling my own products at Dilli Haat was a dream come true. Aagaj made it possible.",
        username: "Fatima Begum, Artisan, Lucknow",
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p8",
    title: "Voter Awareness Rally",
    startDateTime: new Date("2025-03-08T08:00:00").getTime(),
    endDateTime: new Date("2025-03-08T12:00:00").getTime(),
    venueName: "Gandhi Maidan, Patna",
    venueUrl: "https://maps.google.com/?q=Gandhi+Maidan+Patna",
    description: "International Women's Day rally promoting voter awareness and political participation.",
    status: EventStatus.COMPLETED,
    registrationUrl: "",
    coverImage: img(1),
    imageAssets: [img(1), img(2), img(4)],
    hostName: "Aagaj Foundation",
    metrics: [
      { label: "Attendees", value: "500+" },
      { label: "New Voter IDs", value: "80" },
    ],
    createdAt: now,
    updatedAt: now,
  },
];

interface EventStore {
  events: Event[];
  addEvent: (event: Omit<Event, "id" | "createdAt" | "updatedAt">) => void;
  updateEvent: (id: string, data: Partial<Event>) => void;
  deleteEvent: (id: string) => void;
}

export const useEventStore = create<EventStore>((set) => ({
  events: initialEvents,
  addEvent: (event) =>
    set((state) => ({
      events: [
        ...state.events,
        { ...event, id: crypto.randomUUID(), createdAt: Date.now(), updatedAt: Date.now() },
      ],
    })),
  updateEvent: (id, data) =>
    set((state) => ({
      events: state.events.map((e) =>
        e.id === id ? { ...e, ...data, updatedAt: Date.now() } : e
      ),
    })),
  deleteEvent: (id) =>
    set((state) => ({
      events: state.events.filter((e) => e.id !== id),
    })),
}));
